<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVjWEf9W\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVjWEf9W/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVjWEf9W.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVjWEf9W\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVjWEf9W\App_KernelDevDebugContainer([
    'container.build_hash' => 'VjWEf9W',
    'container.build_id' => '5908dba9',
    'container.build_time' => 1744771958,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVjWEf9W');
